# Generated by Django 5.2.8 on 2025-11-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
