# Generated by Django 5.2.8 on 2025-12-12 18:05

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                validators=[store.models.validate_image_file],
            ),
        ),
    ]
